import "@/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { TRPCReactProvider } from "@/trpc/react";
import { AlertProvider } from "../utils/useAlert";
import { CustomAlert } from "@/components/CustomAlert";

export const metadata: Metadata = {
	title: "Absensi Rajawali",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/logo-rajawali.png" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${geist.variable}`}>
			<body>
				<TRPCReactProvider>
					<AlertProvider>
						<CustomAlert />
						{children}
					</AlertProvider>
				</TRPCReactProvider>
			</body>
		</html>
	);
}
